"""Paper Replay Data Models & Enums (PRD v3.9).

Defines immutable records for orders, fills, positions, risk events, and replay reports.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
from typing import Any, Mapping, Sequence


class PaperOrderSide(int, Enum):
    BUY = 1
    SELL = -1
    FLAT = 0


class PaperOrderStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PaperOrderType(str, Enum):
    NEXT_BAR_OPEN = "NEXT_BAR_OPEN"
    MARKET = "MARKET"


@dataclass(frozen=True)
class PaperOrder:
    """An order submitted to the deterministic paper replay simulator."""

    order_id: str
    strategy_id: str
    qualification_id: str
    symbol: str
    side: int  # 1 for Buy/Long, -1 for Sell/Short, 0 for Flat/Exit
    quantity: int
    order_type: str = "NEXT_BAR_OPEN"
    signal_timestamp: str = ""
    submit_timestamp: str = ""
    requested_price: float = 0.0
    status: PaperOrderStatus = PaperOrderStatus.SUBMITTED
    rejection_reason: str | None = None

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError(f"PaperOrder quantity must be positive, got {self.quantity}")
        if self.side not in (1, -1):
            raise ValueError(f"PaperOrder side must be 1 (Buy) or -1 (Sell), got {self.side}")

    def to_dict(self) -> dict[str, Any]:
        return {
            "order_id": self.order_id,
            "strategy_id": self.strategy_id,
            "qualification_id": self.qualification_id,
            "symbol": self.symbol,
            "side": int(self.side),
            "quantity": int(self.quantity),
            "order_type": self.order_type,
            "signal_timestamp": self.signal_timestamp,
            "submit_timestamp": self.submit_timestamp,
            "requested_price": float(self.requested_price),
            "status": self.status.value,
            "rejection_reason": self.rejection_reason,
        }


@dataclass(frozen=True)
class PaperFill:
    """Execution fill generated by the paper execution simulator."""

    fill_id: str
    order_id: str
    strategy_id: str
    symbol: str
    fill_timestamp: str
    fill_price: float
    quantity: int
    side: int
    cost: float
    slippage: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "fill_id": self.fill_id,
            "order_id": self.order_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "fill_timestamp": self.fill_timestamp,
            "fill_price": round(float(self.fill_price), 4),
            "quantity": int(self.quantity),
            "side": int(self.side),
            "cost": round(float(self.cost), 4),
            "slippage": round(float(self.slippage), 4),
        }


@dataclass(frozen=True)
class PaperPosition:
    """Current position state of a strategy in paper replay."""

    symbol: str
    quantity: int  # signed: positive for long, negative for short, 0 for flat
    entry_price: float
    current_price: float
    realized_pnl: float
    unrealized_pnl: float
    fees_costs: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "symbol": self.symbol,
            "quantity": int(self.quantity),
            "entry_price": round(float(self.entry_price), 4),
            "current_price": round(float(self.current_price), 4),
            "realized_pnl": round(float(self.realized_pnl), 4),
            "unrealized_pnl": round(float(self.unrealized_pnl), 4),
            "fees_costs": round(float(self.fees_costs), 4),
        }


@dataclass(frozen=True)
class PaperRiskEvent:
    """Audit record when a paper order is rejected or triggers a risk limit."""

    event_id: str
    order_id: str
    strategy_id: str
    rule_name: str
    limit_value: float
    requested_value: float
    timestamp: str
    reason: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "event_id": self.event_id,
            "order_id": self.order_id,
            "strategy_id": self.strategy_id,
            "rule_name": self.rule_name,
            "limit_value": float(self.limit_value),
            "requested_value": float(self.requested_value),
            "timestamp": self.timestamp,
            "reason": self.reason,
        }


@dataclass(frozen=True)
class ReplaySessionSummary:
    """Summary of trading activity and P&L within a single market session."""

    session_id: str
    start_ts: str
    end_ts: str
    trades: int
    gross_pnl: float
    net_pnl: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "session_id": self.session_id,
            "start_ts": self.start_ts,
            "end_ts": self.end_ts,
            "trades": int(self.trades),
            "gross_pnl": round(float(self.gross_pnl), 4),
            "net_pnl": round(float(self.net_pnl), 4),
        }


@dataclass(frozen=True)
class ReplayReport:
    """Observational report summarizing deterministic paper replay performance.

    Does not make claims or predictions of future profitability.
    """

    strategy_id: str
    qualification_id: str
    dataset_version: str
    trade_count: int
    gross_pnl: float
    net_pnl: float
    costs: float
    slippage: float
    max_drawdown_bps: float
    exposure: float
    win_rate: float
    expectancy: float
    sharpe_ratio: float | None
    session_breakdown: tuple[ReplaySessionSummary, ...]
    report_hash: str
    created_at: str
    strategy_spec_hash: str = ""
    qualification_hash: str = ""
    dataset_sha256: str = ""
    research_protocol_version: str = ""
    symbol: str = "NIFTY_FUT"
    lot_size: int = 50
    tick_size: float = 0.05
    slippage_bps_per_side: float = 0.0
    cost_schedule_id: str = ""
    cost_schedule_hash: str = ""
    risk_config_hash: str = ""
    execution_policy: str = "next_bar_open_v1"
    quantity: int = 1
    hold_bars: int = 1
    initial_capital: float = 100_000.0
    enforce_session_boundaries: bool = True
    split_zone: str = "FORWARD_PAPER"

    @property
    def total_costs(self) -> float:
        return self.costs

    @property
    def total_slippage(self) -> float:
        return self.slippage

    def canonical_dict(self) -> dict[str, Any]:
        return {
            "cost_schedule_hash": self.cost_schedule_hash,
            "cost_schedule_id": self.cost_schedule_id,
            "costs": round(float(self.costs), 4),
            "dataset_sha256": self.dataset_sha256,
            "dataset_version": self.dataset_version,
            "enforce_session_boundaries": bool(self.enforce_session_boundaries),
            "execution_policy": self.execution_policy,
            "expectancy": round(float(self.expectancy), 4),
            "exposure": round(float(self.exposure), 4),
            "gross_pnl": round(float(self.gross_pnl), 4),
            "hold_bars": int(self.hold_bars),
            "initial_capital": round(float(self.initial_capital), 4),
            "lot_size": int(self.lot_size),
            "max_drawdown_bps": round(float(self.max_drawdown_bps), 4),
            "net_pnl": round(float(self.net_pnl), 4),
            "qualification_hash": self.qualification_hash,
            "qualification_id": self.qualification_id,
            "quantity": int(self.quantity),
            "research_protocol_version": self.research_protocol_version,
            "risk_config_hash": self.risk_config_hash,
            "session_breakdown": [s.to_dict() for s in self.session_breakdown],
            "sharpe_ratio": round(float(self.sharpe_ratio), 4) if self.sharpe_ratio is not None else None,
            "slippage": round(float(self.slippage), 4),
            "slippage_bps_per_side": round(float(self.slippage_bps_per_side), 4),
            "split_zone": self.split_zone,
            "strategy_id": self.strategy_id,
            "strategy_spec_hash": self.strategy_spec_hash,
            "symbol": self.symbol,
            "tick_size": round(float(self.tick_size), 4),
            "trade_count": int(self.trade_count),
            "win_rate": round(float(self.win_rate), 4),
        }

    def canonical_json(self) -> str:
        return json.dumps(self.canonical_dict(), sort_keys=True, separators=(",", ":"))

    def compute_report_hash(self) -> str:
        return hashlib.sha256(self.canonical_json().encode("utf-8")).hexdigest()

    @classmethod
    def create(
        cls,
        *,
        strategy_id: str,
        qualification_id: str,
        dataset_version: str,
        trade_count: int,
        gross_pnl: float,
        net_pnl: float,
        costs: float,
        slippage: float,
        max_drawdown_bps: float,
        exposure: float,
        win_rate: float,
        expectancy: float,
        sharpe_ratio: float | None,
        session_breakdown: Sequence[ReplaySessionSummary],
        created_at: str | None = None,
        strategy_spec_hash: str = "",
        qualification_hash: str = "",
        dataset_sha256: str = "",
        research_protocol_version: str = "",
        symbol: str = "NIFTY_FUT",
        lot_size: int = 50,
        tick_size: float = 0.05,
        slippage_bps_per_side: float = 0.0,
        cost_schedule_id: str = "",
        cost_schedule_hash: str = "",
        risk_config_hash: str = "",
        execution_policy: str = "next_bar_open_v1",
        quantity: int = 1,
        hold_bars: int = 1,
        initial_capital: float = 100_000.0,
        enforce_session_boundaries: bool = True,
        split_zone: str = "FORWARD_PAPER",
    ) -> ReplayReport:
        now = created_at or datetime.now(timezone.utc).isoformat()
        temp = cls(
            strategy_id=strategy_id,
            qualification_id=qualification_id,
            dataset_version=dataset_version,
            trade_count=trade_count,
            gross_pnl=gross_pnl,
            net_pnl=net_pnl,
            costs=costs,
            slippage=slippage,
            max_drawdown_bps=max_drawdown_bps,
            exposure=exposure,
            win_rate=win_rate,
            expectancy=expectancy,
            sharpe_ratio=sharpe_ratio,
            session_breakdown=tuple(session_breakdown),
            report_hash="",
            created_at=now,
            strategy_spec_hash=strategy_spec_hash,
            qualification_hash=qualification_hash,
            dataset_sha256=dataset_sha256,
            research_protocol_version=research_protocol_version,
            symbol=symbol,
            lot_size=lot_size,
            tick_size=tick_size,
            slippage_bps_per_side=slippage_bps_per_side,
            cost_schedule_id=cost_schedule_id,
            cost_schedule_hash=cost_schedule_hash,
            risk_config_hash=risk_config_hash,
            execution_policy=execution_policy,
            quantity=quantity,
            hold_bars=hold_bars,
            initial_capital=initial_capital,
            enforce_session_boundaries=enforce_session_boundaries,
            split_zone=split_zone,
        )
        h = temp.compute_report_hash()
        return cls(
            strategy_id=strategy_id,
            qualification_id=qualification_id,
            dataset_version=dataset_version,
            trade_count=trade_count,
            gross_pnl=gross_pnl,
            net_pnl=net_pnl,
            costs=costs,
            slippage=slippage,
            max_drawdown_bps=max_drawdown_bps,
            exposure=exposure,
            win_rate=win_rate,
            expectancy=expectancy,
            sharpe_ratio=sharpe_ratio,
            session_breakdown=tuple(session_breakdown),
            report_hash=h,
            created_at=now,
            strategy_spec_hash=strategy_spec_hash,
            qualification_hash=qualification_hash,
            dataset_sha256=dataset_sha256,
            research_protocol_version=research_protocol_version,
            symbol=symbol,
            lot_size=lot_size,
            tick_size=tick_size,
            slippage_bps_per_side=slippage_bps_per_side,
            cost_schedule_id=cost_schedule_id,
            cost_schedule_hash=cost_schedule_hash,
            risk_config_hash=risk_config_hash,
            execution_policy=execution_policy,
            quantity=quantity,
            hold_bars=hold_bars,
            initial_capital=initial_capital,
            enforce_session_boundaries=enforce_session_boundaries,
            split_zone=split_zone,
        )
